project:
  type: website

website:
  title: "Catch Them All"
  navbar:
    left: 
      - href: intro.qmd
        text: Project Scope
      - href: methodology.qmd
        text: Methodology
      - href: data.qmd
        text: Data
      - href: results.qmd
        text: Results & Discussion
    right:
      - href: index.qmd
        text: Overview
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

